version: '2.2'
services:
  filling:
    build:
      context: .
      dockerfile: Dockerfile
    image: zihjiang/filling:latest
    container_name: filling
    depends_on:
      - jobmanager
      - taskmanager
    environment:
      - _JAVA_OPTIONS=-Xmx1g -Xms1g
      - JHIPSTER_SLEEP=10 # gives time for the JHipster Registry to boot before the application
      - SPRING_PROFILES_ACTIVE=docker
      - application_flink_url=http://jobmanager:8081
    ports:
      - "8080:8080"
  jobmanager:
    image: flink:1.14.3-scala_2.11-java11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    image: flink:1.14.3-scala_2.11-java11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 4
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3
